id: P007933
initial_creation_type: ocr
source_metadata:
  id: bdr:W525
  title: གསང་འདུས་རྫོགས་རིམ་རིམ་ལྔ་གདན་རྫོགས་དམར་ཁྲིད།
  author: ''
  volumes:
    92067da58e5d45ab8ceca4717ae47c8d:
      image_group_id: I1KG18225
      title: ''
      volume_number: 1
      total_pages: 190
ebook_metadata:
  title: གསང་འདུས་རྫོགས་རིམ་རིམ་ལྔ་གདན་རྫོགས་དམར་ཁྲིད།
  author: ''
  sku: P007933
  cover: cover.jpg
  layers:
  - pagination
