id: P007933
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W525
  title: གསང་འདུས་རྫོགས་རིམ་རིམ་ལྔ་གདན་རྫོགས་དམར་ཁྲིད།
  author: ''
  volumes:
    eaffb3d8984a4f75bd859d6b0b036947:
      image_group_id: I1KG18225
      title: Volume 1 of gsang 'dus rdzogs rim rim lnga gdan rdzogs dmar khrid/
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
