id: opecha:P007933
initial_creation_type: ocr
source_metadata:
  id: bdr:W525
  title: གསང་འདུས་རྫོགས་རིམ་རིམ་ལྔ་གདན་རྫོགས་དམར་ཁྲིད།
  volume:
    eaffb3d8984a4f75bd859d6b0b036947:
      image_group_id: I1KG18225
      title: Volume 1 of gsang 'dus rdzogs rim rim lnga gdan rdzogs dmar khrid/
      volume_number: 1
      total_pages: 190
  author: ''
ebook_metadata:
  title: གསང་འདུས་རྫོགས་རིམ་རིམ་ལྔ་གདན་རྫོགས་དམར་ཁྲིད།
  author: ''
  sku: P007933
  cover: cover.jpg
  layers:
  - pagination
