id: ID6CF4B0B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:31:50+00:00'
last_modified: '2022-06-09T07:41:13.900996+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W525
  title: གསང་འདུས་རྫོགས་རིམ་རིམ་ལྔ་གདན་རྫོགས་དམར་ཁྲིད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9E9A:
      image_group_id: I1KG18225
      title: Volume 1 of gsang 'dus rdzogs rim rim lnga gdan rdzogs dmar khrid/
      total_pages: 190
      order: 1
      base_file: 9E9A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
